apiVersion: batch/v1
kind: CronJob
metadata:
  name: alarmbot
spec:
  schedule: "*/1 * * * *"
  #schedule: "0 9 * * 1-5"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alarmbot
            image: AWS_ECR_URI_ALARM
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure