apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: alarmbot
spec:
  schedule: "*/1 * * * 1-5"
  #schedule: "0 9 * * 1-5"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alarmbot
            image: 388265291349.dkr.ecr.ap-northeast-2.amazonaws.com/goorm/telegram-alarm:ALARM-0edf
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure