---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 388265291349.dkr.ecr.ap-northeast-2.amazonaws.com/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3100
          env:
            - name: DATE
              value: 'DATE_STRING'
