# ./buildspec.yaml

version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - mkdir ~/.kube
      - aws eks --region ap-northeast-2 update-kubeconfig --name eks
      - kubectl get po -n kube-system
    pre_build:
      commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/
    build:
      commands:
       - echo Building the Docker image
       - docker build -f ./client/dockerfile -t $IMAGE_REPO_NAMEF:$IMAGE_TAG .
       - docker build -f ./server/dockerfile -t $IMAGE_REPO_NAMEB:$IMAGE_TAG .
       
       - docker tag $IMAGE_REPO_NAMEF:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAMEF:$IMAGE_TAG
       - docker tag $IMAGE_REPO_NAMEB:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAMEB:$IMAGE_TAG
       
       - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAMEF:$IMAGE_TAG
       - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAMEB:$IMAGE_TAG

    post_build:
      commands:
       - AWS_ECR_URIF=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAMEF:$IMAGE_TAG
       - AWS_ECR_URIB=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAMEB:$IMAGE_TAG
       
       - DATE=`date`
       - echo Build completed on $DATE
       
       - sed -i.bak 's#AWS_ECR_URIF#'"$AWS_ECR_URIF"'#' ./manifests/frontend-deployment.yaml
       - sed -i.bak 's#AWS_ECR_URIB#'"$AWS_ECR_URIB"'#' ./manifests/backend-deployment.yaml       
       - sed -i.bak 's#DATE_STRING#'"$DATE"'#' ./manifests/frontend-deployment.yaml
       - sed -i.bak 's#DATE_STRING#'"$DATE"'#' ./manifests/backend-deployment.yaml
       
       - kubectl apply -f ./manifests/backend-deployment.yaml
       - kubectl apply -f ./manifests/backend-service.yaml
       - kubectl apply -f ./manifests/frontend-deployment.yaml
       - kubectl apply -f ./manifests/frontend-service.yaml
       - kubectl apply -f ./manifests/ingress.yaml
