# ./buildspec.yaml

version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - mkdir ~/.kube
      - aws eks --region ap-northeast-2 update-kubeconfig --name eks
      - kubectl get po -n kube-system
    pre_build:
      commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/
      - COMMIT_HASH1=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-4)
      - COMMIT_HASH2=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 5-8)
      - webF_IMAGE_TAG=F-${COMMIT_HASH1:=latest}
      - webB_IMAGE_TAG=B-${COMMIT_HASH2:=latest}
    build:
      commands:

       - echo Build completed on 'date'
       - echo Building the Docker image started on DATE
       
       - docker build -f ./client/dockerfile -t $IMAGE_REPO_NAMEF:$webF_IMAGE_TAG .
       - docker build -f ./server/dockerfile -t $IMAGE_REPO_NAMEB:$webB_IMAGE_TAG .
       
       - docker tag $IMAGE_REPO_NAMEF:$webF_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAMEF:$webF_IMAGE_TAG
       - docker tag $IMAGE_REPO_NAMEB:$webB_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAMEB:$webB_IMAGE_TAG
       
       - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAMEF:$webF_IMAGE_TAG
       - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAMEB:$webB_IMAGE_TAG

    post_build:
      commands:
       - AWS_ECR_URIF=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAMEF:$webF_IMAGE_TAG
       - AWS_ECR_URIB=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAMEB:$webB_IMAGE_TAG
       
       - sed -i.bak 's#AWS_ECR_URIF#'"$AWS_ECR_URIF"'#' ./manifests/frontend-deployment.yaml
       - sed -i.bak 's#AWS_ECR_URIB#'"$AWS_ECR_URIB"'#' ./manifests/backend-deployment.yaml       
       - sed -i.bak 's#DATE_STRING#'"$DATE"'#' ./manifests/frontend-deployment.yaml
       - sed -i.bak 's#DATE_STRING#'"$DATE"'#' ./manifests/backend-deployment.yaml
       
       - kubectl apply -f ./manifests/backend-deployment.yaml
       - kubectl apply -f ./manifests/backend-service.yaml
       - kubectl apply -f ./manifests/frontend-deployment.yaml
       - kubectl apply -f ./manifests/frontend-service.yaml
       - kubectl apply -f ./manifests/ingress.yaml
