---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: demo-frontend
          image: 388265291349.dkr.ecr.ap-northeast-2.amazonaws.com/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
